#       makefile for ruletree458fall2017 project csc458 project 2
#       Dr. Dale Parson. Fall 2017

all:		test

TARGET = ruletree458fall2017

include ./makelib

clean:		subclean

test:
			chmod +x ./checkfiles.sh && ./checkfiles.sh
