#!/bin/bash

# check versions of Python and the machine

# set -x
machine=`uname -n`
ispy=`echo $machine | grep -i "kupapcsit01" | wc -l`
isbill=`echo $machine | grep -i "v245" | wc -l`
if [ $isbill == 1 ]
then
    echo "Please use 'ssh -l LOGINNAME harry|hermione|ron'"
    exit 1
fi
if [ $ispy == 0 ]
then
    echo "Please set up your PATH for Python version 2.6.x or 2.7.x"
    exit 2
fi
exit 0
